In [1]:
import pandas as pd

In [2]:
russ = pd.read_csv('Russ_1000_copy.csv')
fins = pd.read_csv('scraped_df.csv')
bonds = pd.read_csv('bond_df_copy.csv')

In [3]:
russ.head()

,Ticker,Name,Asset Class,Weight (%),Price,Shares,Market Value,Notional Value,Sector,SEDOL,ISIN,Exchange
0,AAPL,APPLE INC,Equity,4.62,324.95,"3,327,521.00","1,081,277,948.95","1,081,277,948.95",Information Technology,2046251,US0378331005,NASDAQ
1,MSFT,MICROSOFT CORP,Equity,4.49,185.35,"5,661,995.00","1,049,450,773.25","1,049,450,773.25",Information Technology,2588173,US5949181045,NASDAQ
2,AMZN,AMAZON COM INC,Equity,2.83,"2,134.87","309,633.00","661,026,202.71","661,026,202.71",Consumer Discretionary,2000019,US0231351067,NASDAQ
3,FB,FACEBOOK CLASS A INC,Equity,1.64,214.18,"1,788,162.00","382,988,537.16","382,988,537.16",Communication,B7TL820,US30303M1027,NASDAQ
4,GOOG,ALPHABET INC CLASS C,Equity,1.46,"1,520.74","224,375.00","341,216,037.50","341,216,037.50",Communication,BYY88Y7,US02079K1079,NASDAQ

In [4]:
fins.head()

,Unnamed: 0,Market Cap (intraday) 5,Enterprise Value 3,Trailing P/E,Forward P/E 1,PEG Ratio (5 yr expected) 1,Price/Sales (ttm),Price/Book (mrq),Enterprise Value/Revenue 3,Enterprise Value/EBITDA 6,...,Quarterly Earnings Growth (yoy),Total Cash (mrq),Total Cash Per Share (mrq),Total Debt (mrq),Total Debt/Equity (mrq),Current Ratio (mrq),Book Value Per Share (mrq),Operating Cash Flow (ttm),Levered Free Cash Flow (ttm),Tickers
0,1,1.31T,1.21T,23.72,19.06,1.66,4.88,14.63,4.50,15.43,...,11.40%,107.16B,24.49,116.75B,130.40,1.60,20.42,73.22B,45.59B,AAPL
1,1,1.31T,1.19T,30.10,27.38,1.92,9.79,11.94,8.83,19.34,...,38.30%,134.23B,17.65,87.15B,79.15,2.80,14.47,54.13B,35.08B,MSFT
2,1,972.7B,960.26B,84.92,48.63,2.18,3.47,15.68,3.42,26.53,...,8.00%,55.02B,110.53,77.54B,124.94,1.10,124.62,38.51B,18.79B,AMZN
3,1,559.94B,504.85B,30.55,18.01,1.60,7.92,5.54,7.14,16.98,...,6.80%,54.86B,19.24,11.07B,10.96,4.40,35.43,36.31B,15.85B,FB
4,1,954.69B,816.79B,28.26,22.16,1.57,5.90,4.75,5.05,16.97,...,19.30%,119.68B,174.13,15.97B,7.93,3.37,292.65,54.52B,25.58B,GOOG

In [5]:
fins.shape

(800, 77)

In [6]:
russ.shape

(1001, 12)

In [7]:
fins['Ticker'] = fins['Tickers']

In [8]:
fins = fins.drop(columns='Tickers')

In [9]:
fins

,Unnamed: 0,Market Cap (intraday) 5,Enterprise Value 3,Trailing P/E,Forward P/E 1,PEG Ratio (5 yr expected) 1,Price/Sales (ttm),Price/Book (mrq),Enterprise Value/Revenue 3,Enterprise Value/EBITDA 6,...,Quarterly Earnings Growth (yoy),Total Cash (mrq),Total Cash Per Share (mrq),Total Debt (mrq),Total Debt/Equity (mrq),Current Ratio (mrq),Book Value Per Share (mrq),Operating Cash Flow (ttm),Levered Free Cash Flow (ttm),Ticker
0,1,1.31T,1.21T,23.72,19.06,1.66,4.88,14.63,4.50,15.43,...,11.40%,107.16B,24.49,116.75B,130.40,1.60,20.42,73.22B,45.59B,AAPL
1,1,1.31T,1.19T,30.10,27.38,1.92,9.79,11.94,8.83,19.34,...,38.30%,134.23B,17.65,87.15B,79.15,2.80,14.47,54.13B,35.08B,MSFT
2,1,972.7B,960.26B,84.92,48.63,2.18,3.47,15.68,3.42,26.53,...,8.00%,55.02B,110.53,77.54B,124.94,1.10,124.62,38.51B,18.79B,AMZN
3,1,559.94B,504.85B,30.55,18.01,1.60,7.92,5.54,7.14,16.98,...,6.80%,54.86B,19.24,11.07B,10.96,4.40,35.43,36.31B,15.85B,FB
4,1,954.69B,816.79B,28.26,22.16,1.57,5.90,4.75,5.05,16.97,...,19.30%,119.68B,174.13,15.97B,7.93,3.37,292.65,54.52B,25.58B,GOOG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,1,3.83B,7.89B,11.18,5.18,1.34,0.67,1.45,1.38,8.11,...,5.00%,237M,1.59,4.27B,163.65,0.77,17.51,670M,2.25B,CPRI
796,1,3.88B,5.37B,8.40,9.49,0.94,3.42,0.78,4.73,NaN,...,2.50%,637.86M,5.53,2.36B,NaN,NaN,41.89,582.66M,NaN,PACW
797,1,3.92B,1.19B,8.24,61.81,-35.35,30.67,1.25,9.31,25.75,...,3.70%,2.8B,22.91,26.57M,0.82,63.11,25.63,98.94M,60.43M,EQC
798,1,5.24B,12.1B,6.55,8.25,-0.62,0.32,1.44,0.74,6.34,...,-47.40%,1.08B,2.90,7.83B,215.55,1.43,9.74,1.34B,146.12M,GPS
799,1,4.44B,5.7B,90.62,15.69,1.58,2.92,3.19,3.76,15.40,...,-39.10%,198.92M,2.36,1.5B,106.09,2.59,16.50,231.43M,130.68M,IART

In [10]:
df = pd.merge(russ, fins, on='Ticker')

In [11]:
df.head()

,Ticker,Name,Asset Class,Weight (%),Price,Shares,Market Value,Notional Value,Sector,SEDOL,...,Diluted EPS (ttm),Quarterly Earnings Growth (yoy),Total Cash (mrq),Total Cash Per Share (mrq),Total Debt (mrq),Total Debt/Equity (mrq),Current Ratio (mrq),Book Value Per Share (mrq),Operating Cash Flow (ttm),Levered Free Cash Flow (ttm)
0,AAPL,APPLE INC,Equity,4.62,324.95,"3,327,521.00","1,081,277,948.95","1,081,277,948.95",Information Technology,2046251,...,12.60,11.40%,107.16B,24.49,116.75B,130.40,1.60,20.42,73.22B,45.59B
1,MSFT,MICROSOFT CORP,Equity,4.49,185.35,"5,661,995.00","1,049,450,773.25","1,049,450,773.25",Information Technology,2588173,...,5.74,38.30%,134.23B,17.65,87.15B,79.15,2.80,14.47,54.13B,35.08B
2,AMZN,AMAZON COM INC,Equity,2.83,"2,134.87","309,633.00","661,026,202.71","661,026,202.71",Consumer Discretionary,2000019,...,23.01,8.00%,55.02B,110.53,77.54B,124.94,1.10,124.62,38.51B,18.79B
3,FB,FACEBOOK CLASS A INC,Equity,1.64,214.18,"1,788,162.00","382,988,537.16","382,988,537.16",Communication,B7TL820,...,6.43,6.80%,54.86B,19.24,11.07B,10.96,4.40,35.43,36.31B,15.85B
4,GOOG,ALPHABET INC CLASS C,Equity,1.46,"1,520.74","224,375.00","341,216,037.50","341,216,037.50",Communication,BYY88Y7,...,49.16,19.30%,119.68B,174.13,15.97B,7.93,3.37,292.65,54.52B,25.58B

In [12]:
df1 = df.Name.str.lower()

In [13]:
df1.head(10)

0                         apple inc
1                    microsoft corp
2                    amazon com inc
3              facebook class a inc
4              alphabet inc class c
5              alphabet inc class a
6    berkshire hathaway inc class b
7               jpmorgan chase & co
8                 johnson & johnson
9                  visa inc class a
Name: Name, dtype: object

In [14]:
df['Names'] = df1

In [15]:
df

,Ticker,Name,Asset Class,Weight (%),Price,Shares,Market Value,Notional Value,Sector,SEDOL,...,Quarterly Earnings Growth (yoy),Total Cash (mrq),Total Cash Per Share (mrq),Total Debt (mrq),Total Debt/Equity (mrq),Current Ratio (mrq),Book Value Per Share (mrq),Operating Cash Flow (ttm),Levered Free Cash Flow (ttm),Names
0,AAPL,APPLE INC,Equity,4.62,324.95,"3,327,521.00","1,081,277,948.95","1,081,277,948.95",Information Technology,2046251,...,11.40%,107.16B,24.49,116.75B,130.40,1.60,20.42,73.22B,45.59B,apple inc
1,MSFT,MICROSOFT CORP,Equity,4.49,185.35,"5,661,995.00","1,049,450,773.25","1,049,450,773.25",Information Technology,2588173,...,38.30%,134.23B,17.65,87.15B,79.15,2.80,14.47,54.13B,35.08B,microsoft corp
2,AMZN,AMAZON COM INC,Equity,2.83,"2,134.87","309,633.00","661,026,202.71","661,026,202.71",Consumer Discretionary,2000019,...,8.00%,55.02B,110.53,77.54B,124.94,1.10,124.62,38.51B,18.79B,amazon com inc
3,FB,FACEBOOK CLASS A INC,Equity,1.64,214.18,"1,788,162.00","382,988,537.16","382,988,537.16",Communication,B7TL820,...,6.80%,54.86B,19.24,11.07B,10.96,4.40,35.43,36.31B,15.85B,facebook class a inc
4,GOOG,ALPHABET INC CLASS C,Equity,1.46,"1,520.74","224,375.00","341,216,037.50","341,216,037.50",Communication,BYY88Y7,...,19.30%,119.68B,174.13,15.97B,7.93,3.37,292.65,54.52B,25.58B,alphabet inc class c
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,CPRI,CAPRI HOLDINGS LTD,Equity,0.01,28.62,"109,635.00","3,137,753.70","3,137,753.70",Consumer Discretionary,BJ1N1M9,...,5.00%,237M,1.59,4.27B,163.65,0.77,17.51,670M,2.25B,capri holdings ltd
796,PACW,PACWEST BANCORP,Equity,0.01,37.09,"84,473.00","3,133,103.57","3,133,103.57",Financials,2619772,...,2.50%,637.86M,5.53,2.36B,NaN,NaN,41.89,582.66M,NaN,pacwest bancorp
797,EQC,EQUITY COMMONWEALTH REIT,Equity,0.01,33.29,"93,949.00","3,127,562.21","3,127,562.21",Real Estate,BPH3N63,...,3.70%,2.8B,22.91,26.57M,0.82,63.11,25.63,98.94M,60.43M,equity commonwealth reit
798,GPS,GAP INC,Equity,0.01,18.14,"172,284.00","3,125,231.76","3,125,231.76",Consumer Discretionary,2360326,...,-47.40%,1.08B,2.90,7.83B,215.55,1.43,9.74,1.34B,146.12M,gap inc
799,IART,INTEGRA LIFESCIENCES HOLDINGS CORP,Equity,0.01,58.93,"52,993.00","3,122,877.49","3,122,877.49",Health Care,2248693,...,-39.10%,198.92M,2.36,1.5B,106.09,2.59,16.50,231.43M,130.68M,integra lifesciences holdings corp

In [16]:
df['Names'] = df['Names'].str.replace('.', '')

In [17]:
df['Names'] = df['Names'].str.replace('-', '')

In [18]:
df['Names'] = df['Names'].str.replace('&', '')

In [19]:
df['Names'] = df['Names'].str.replace(' ', '')

In [20]:
df['Names'] = df['Names'].str[:6]

In [21]:
# df['new_col'] =

In [22]:
# df['Names'].str[:5]

In [23]:
pd.set_option("display.max_rows", 100)

In [24]:
df.head(6)

,Ticker,Name,Asset Class,Weight (%),Price,Shares,Market Value,Notional Value,Sector,SEDOL,...,Quarterly Earnings Growth (yoy),Total Cash (mrq),Total Cash Per Share (mrq),Total Debt (mrq),Total Debt/Equity (mrq),Current Ratio (mrq),Book Value Per Share (mrq),Operating Cash Flow (ttm),Levered Free Cash Flow (ttm),Names
0,AAPL,APPLE INC,Equity,4.62,324.95,"3,327,521.00","1,081,277,948.95","1,081,277,948.95",Information Technology,2046251,...,11.40%,107.16B,24.49,116.75B,130.40,1.60,20.42,73.22B,45.59B,applei
1,MSFT,MICROSOFT CORP,Equity,4.49,185.35,"5,661,995.00","1,049,450,773.25","1,049,450,773.25",Information Technology,2588173,...,38.30%,134.23B,17.65,87.15B,79.15,2.80,14.47,54.13B,35.08B,micros
2,AMZN,AMAZON COM INC,Equity,2.83,"2,134.87","309,633.00","661,026,202.71","661,026,202.71",Consumer Discretionary,2000019,...,8.00%,55.02B,110.53,77.54B,124.94,1.10,124.62,38.51B,18.79B,amazon
3,FB,FACEBOOK CLASS A INC,Equity,1.64,214.18,"1,788,162.00","382,988,537.16","382,988,537.16",Communication,B7TL820,...,6.80%,54.86B,19.24,11.07B,10.96,4.40,35.43,36.31B,15.85B,facebo
4,GOOG,ALPHABET INC CLASS C,Equity,1.46,"1,520.74","224,375.00","341,216,037.50","341,216,037.50",Communication,BYY88Y7,...,19.30%,119.68B,174.13,15.97B,7.93,3.37,292.65,54.52B,25.58B,alphab
5,GOOGL,ALPHABET INC CLASS A,Equity,1.45,"1,518.73","224,028.00","340,238,044.44","340,238,044.44",Communication,BYVY8G0,...,19.30%,119.68B,174.13,15.97B,7.93,3.37,292.65,54.52B,25.58B,alphab

In [25]:
df[['Market Cap (intraday) 5']]

    Market Cap (intraday) 5
0                     1.31T
1                     1.31T
2                    972.7B
3                   559.94B
4                   954.69B
..                      ...
795                   3.83B
796                   3.88B
797                   3.92B
798                   5.24B
799                   4.44B

[800 rows x 1 columns]

In [26]:
bonds.head()

,Unnamed: 0,Issuer,Currency,Coupon,Yield,Moody's Rating,Maturity Date,Bid,Ask
0,0,000000,USD,6.5000%,-,Aa2,10/1/2034,130.00,-
1,1,000000,USD,7.7500%,407.08%,NaN,10/1/2022,3.30,11.75
2,2,21st Century Fox America Inc.,USD,6.5500%,3.26%,WR,3/15/2033,134.49,140.08
3,3,21st Century Fox America Inc.,USD,6.1500%,4.24%,WR,3/1/2037,122.80,133.50
4,4,21st Century Fox America Inc.,USD,4.7500%,4.16%,WR,11/15/2046,-,-

In [27]:
bonds['Names'] = bonds['Issuer']

In [28]:
df2 = bonds.Names.str.lower()

In [29]:
bonds['Names'] = df2

In [30]:
bonds

,Unnamed: 0,Issuer,Currency,Coupon,Yield,Moody's Rating,Maturity Date,Bid,Ask,Names
0,0,000000,USD,6.5000%,-,Aa2,10/1/2034,130.00,-,000000
1,1,000000,USD,7.7500%,407.08%,NaN,10/1/2022,3.30,11.75,000000
2,2,21st Century Fox America Inc.,USD,6.5500%,3.26%,WR,3/15/2033,134.49,140.08,21st century fox america inc.
3,3,21st Century Fox America Inc.,USD,6.1500%,4.24%,WR,3/1/2037,122.80,133.50,21st century fox america inc.
4,4,21st Century Fox America Inc.,USD,4.7500%,4.16%,WR,11/15/2046,-,-,21st century fox america inc.
...,...,...,...,...,...,...,...,...,...,...
7000,7000,eBay Inc.,USD,2.8750%,2.06%,Baa1,8/1/2021,101.19,101.47,ebay inc.
7001,7001,eBay Inc.,USD,2.6000%,2.27%,Baa1,7/15/2022,100.91,101.1,ebay inc.
7002,7002,iStar Inc.,USD,4.7500%,4.08%,Ba3,10/1/2024,102.79,103.64,istar inc.
7003,7003,salesforce.com Inc.,USD,3.7000%,2.39%,A3,4/11/2028,109.63,110.57,salesforce.com inc.
7004,7004,salesforce.com Inc.,USD,3.2500%,1.98%,A3,4/11/2023,103.9,104.2,salesforce.com inc.

In [31]:
bonds['Names'] = bonds['Names'].str.replace('.', '')

In [32]:
bonds['Names'] = bonds['Names'].str.replace('-', '')

In [33]:
bonds['Names'] = bonds['Names'].str.replace('&', '')

In [34]:
bonds['Names'] = bonds['Names'].str.replace(' ', '')

In [35]:
bonds['Names'] = bonds['Names'].str[:6]

In [36]:
# df['new_col'] =

In [37]:
# df['Names'].str[:5]

In [38]:
bonds

,Unnamed: 0,Issuer,Currency,Coupon,Yield,Moody's Rating,Maturity Date,Bid,Ask,Names
0,0,000000,USD,6.5000%,-,Aa2,10/1/2034,130.00,-,000000
1,1,000000,USD,7.7500%,407.08%,NaN,10/1/2022,3.30,11.75,000000
2,2,21st Century Fox America Inc.,USD,6.5500%,3.26%,WR,3/15/2033,134.49,140.08,21stce
3,3,21st Century Fox America Inc.,USD,6.1500%,4.24%,WR,3/1/2037,122.80,133.50,21stce
4,4,21st Century Fox America Inc.,USD,4.7500%,4.16%,WR,11/15/2046,-,-,21stce
...,...,...,...,...,...,...,...,...,...,...
7000,7000,eBay Inc.,USD,2.8750%,2.06%,Baa1,8/1/2021,101.19,101.47,ebayin
7001,7001,eBay Inc.,USD,2.6000%,2.27%,Baa1,7/15/2022,100.91,101.1,ebayin
7002,7002,iStar Inc.,USD,4.7500%,4.08%,Ba3,10/1/2024,102.79,103.64,istari
7003,7003,salesforce.com Inc.,USD,3.7000%,2.39%,A3,4/11/2028,109.63,110.57,salesf
7004,7004,salesforce.com Inc.,USD,3.2500%,1.98%,A3,4/11/2023,103.9,104.2,salesf

In [39]:
df_end = pd.merge(bonds, df, on='Names')

In [40]:
df_end

,Unnamed: 0_x,Issuer,Currency,Coupon,Yield,Moody's Rating,Maturity Date,Bid,Ask,Names,...,Diluted EPS (ttm),Quarterly Earnings Growth (yoy),Total Cash (mrq),Total Cash Per Share (mrq),Total Debt (mrq),Total Debt/Equity (mrq),Current Ratio (mrq),Book Value Per Share (mrq),Operating Cash Flow (ttm),Levered Free Cash Flow (ttm)
0,44,AECOM,USD,5.1250%,4.21%,Ba3,3/15/2027,105.51,107.01,aecom,...,-1.73,-21.20%,725.44M,4.57,4.39B,113.70,1.16,23.22,771.07M,513.58M
1,45,AECOM,USD,5.8750%,3.54%,Ba3,10/15/2024,109.86,111.14,aecom,...,-1.73,-21.20%,725.44M,4.57,4.39B,113.70,1.16,23.22,771.07M,513.58M
2,49,AFLAC Inc.,USD,3.2500%,3.58%,A3,3/17/2025,98.50,101.50,aflaci,...,4.43,48.80%,5.53B,7.65,8.45B,29.16,0.57,39.85,5.46B,2.72B
3,50,AFLAC Inc.,USD,4.0000%,3.44%,A3,10/15/2046,106.38,112.26,aflaci,...,4.43,48.80%,5.53B,7.65,8.45B,29.16,0.57,39.85,5.46B,2.72B
4,51,AFLAC Inc.,USD,6.4500%,-,A3,8/15/2040,-,110.88,aflaci,...,4.43,48.80%,5.53B,7.65,8.45B,29.16,0.57,39.85,5.46B,2.72B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6937,6999,eBay Inc.,USD,4.0000%,4.16%,Baa1,7/15/2042,97.76,98.63,ebayin,...,2.09,-26.80%,2.82B,3.55,8.42B,293.45,1.16,3.61,3.11B,2.24B
6938,7000,eBay Inc.,USD,2.8750%,2.06%,Baa1,8/1/2021,101.19,101.47,ebayin,...,2.09,-26.80%,2.82B,3.55,8.42B,293.45,1.16,3.61,3.11B,2.24B
6939,7001,eBay Inc.,USD,2.6000%,2.27%,Baa1,7/15/2022,100.91,101.1,ebayin,...,2.09,-26.80%,2.82B,3.55,8.42B,293.45,1.16,3.61,3.11B,2.24B
6940,7003,salesforce.com Inc.,USD,3.7000%,2.39%,A3,4/11/2028,109.63,110.57,salesf,...,0.90,NaN,6.53B,7.36,6.49B,19.51,1.05,37.56,4.03B,5.14B
6941,7004,salesforce.com Inc.,USD,3.2500%,1.98%,A3,4/11/2023,103.9,104.2,salesf,...,0.90,NaN,6.53B,7.36,6.49B,19.51,1.05,37.56,4.03B,5.14B

In [41]:
df_end.Names.unique()

array(['aecom', 'aflaci', 'attinc', 'abbvie', 'abbott', 'activi',
       'adobei', 'advanc', 'agilen', 'airlea', 'airpro', 'albema',
       'alexan', 'allegh', 'allegi', 'allerg', 'allian', 'alliso',
       'allyfi', 'alphab', 'altria', 'amazon', 'ameren', 'americ',
       'amerip', 'ameris', 'amgeni', 'amphen', 'analog', 'anthem',
       'apache', 'applei', 'applie', 'aramar', 'archer', 'arconi',
       'arrowe', 'ashlan', 'assura', 'assure', 'atmose', 'autozo',
       'autode', 'automa', 'avalon', 'avanto', 'averyd', 'bwxtec',
       'bakerh', 'ballco', 'bankof', 'baxter', 'becton', 'berksh',
       'berryg', 'bestbu', 'biorad', 'biogen', 'blackr', 'boeing',
       'bookin', 'borgwa', 'boston', 'bright', 'bristo', 'brixmo',
       'broadc', 'broadr', 'brownb', 'brownf', 'brunsw', 'bungel',
       'burlin', 'chrobi', 'cdkglo', 'cfindu', 'citgro', 'cmegro',
       'cmsene', 'csxcor', 'cvshea', 'caesar', 'camden', 'campbe',
       'capita', 'cardin', 'carlis', 'carvan', 'catale', 'caterp',
       'celane', 'centen', 'center', 'centur', 'charle', 'charte',
       'chevro', 'church', 'cignac', 'cincin', 'ciscos', 'citigr',
       'citize', 'citrix', 'cleanh', 'cocaco', 'colgat', 'comcas',
       'comeri', 'commer', 'conagr', 'concho', 'conoco', 'consol',
       'conste', 'cooper', 'cornin', 'costco', 'credit', 'crownc',
       'crownh', 'cubesm', 'cummin', 'drhort', 'dteene', 'dxctec',
       'davita', 'danahe', 'darden', 'deltaa', 'devone', 'diamon',
       'digita', 'discov', 'dollar', 'domini', 'doverc', 'dupont',
       'dukeen', 'dukere', 'eogres', 'eprpro', 'eastma', 'ecolab',
       'edison', 'edward', 'elanco', 'electr', 'elilil', 'emerso',
       'encomp', 'enterg', 'equifa', 'equini', 'essent', 'essexp',
       'everes', 'evergy', 'everso', 'exelon', 'expedi', 'exxonm',
       'fmccor', 'federa', 'fedexc', 'fideli', 'fiftht', 'firsta',
       'firsth', 'firste', 'fiserv', 'flirsy', 'flower', 'flowse',
       'fordmo', 'fortiv', 'fortun', 'foxcor', 'frankl', 'freepo',
       'gapinc', 'genera', 'gilead', 'global', 'globel', 'goldma',
       'graphi', 'hcahea', 'hdsupp', 'hpinc', 'hallib', 'hanesb',
       'harley', 'health', 'hessco', 'hewlet', 'hexcel', 'highwo',
       'hillro', 'hilton', 'hollyf', 'hologi', 'honeyw', 'hostho',
       'hubbel', 'hudson', 'humana', 'huntin', 'huntsm', 'iaainc',
       'idexco', 'illino', 'ingers', 'ingred', 'insule', 'integr',
       'intelc', 'interc', 'intern', 'ironmo', 'jmsmuc', 'jpmorg',
       'jabili', 'jacobs', 'jeffer', 'jetblu', 'johnso', 'junipe',
       'klacor', 'kansas', 'kellog', 'keurig', 'keycor', 'keysig',
       'kilroy', 'kimber', 'kimcor', 'kinder', 'kirbyc', 'krafth',
       'lbrand', 'l3harr', 'labora', 'lamres', 'lambwe', 'lasveg',
       'learco', 'legget', 'leidos', 'lennar', 'lennox', 'libert',
       'lifest', 'lincol', 'livena', 'lockhe', 'mgmres', 'msciin',
       'marath', 'markel', 'marrio', 'marshm', 'martin', 'mascoc',
       'master', 'mattel', 'maximi', 'mccorm', 'mcdona', 'mckess',
       'medtro', 'merckc', 'metlif', 'micron', 'micros', 'midame',
       'mohawk', 'molson', 'mondel', 'morgan', 'mosaic', 'motoro',
       'ncrcor', 'nikein', 'nisour', 'nrgene', 'nvidia', 'nvrinc',
       'nasdaq', 'nation', 'netapp', 'netfli', 'newyor', 'newell',
       'newmon', 'nexter', 'noblee', 'nordst', 'norfol', 'northe',
       'northr', 'norton', 'nucorc', 'occide', 'oldrep', 'omegah',
       'omnico', 'oneoki', 'oracle', 'oshkos', 'owensc', 'pgecor',
       'ppgind', 'ptcinc', 'pvhcor', 'paccar', 'packag', 'parker',
       'parsle', 'paypal', 'pepsic', 'perkin', 'pfizer', 'philip',
       'philli', 'pinnac', 'pionee', 'postho', 'princi', 'progre',
       'prolog', 'pruden', 'public', 'pulteg', 'qualco', 'qorvoi',
       'questd', 'rpmint', 'ralphl', 'raymon', 'raythe', 'realty',
       'regenc', 'region', 'reinsu', 'relian', 'republ', 'rockwe',
       'ropert', 'spglob', 'slgree', 'slmcor', 'svbfin', 'schlum',
       'sempra', 'servic', 'sherwi', 'simonp', 'sirius', 'snapon',
       'sonoco', 'southe', 'southw', 'spirit', 'sprint', 'stanle',
       'starbu', 'starwo', 'states', 'steeld', 'steric', 'storec',
       'stryke', 'synchr', 'syscoc', 'tmobil', 'tdamer', 'tapest',
       'targar', 'target', 'telefl', 'tempur', 'teslai', 'texasi',
       'textro', 'thermo', 'tiffan', 'tollbr', 'transd', 'travel',
       'trimbl', 'truist', 'tysonf', 'usbanc', 'usfood', 'uberte',
       'unionp', 'united', 'univer', 'vfcorp', 'vereit', 'visain',
       'vmware', 'valero', 'valvol', 'ventas', 'verisi', 'verisk',
       'verizo', 'viacom', 'vistra', 'vornad', 'voyafi', 'vulcan',
       'wpcare', 'wrberk', 'wwgrai', 'wecene', 'wpxene', 'walgre',
       'walmar', 'wastem', 'wellsf', 'wellto', 'westro', 'wester',
       'weyerh', 'whirlp', 'willia', 'wyndha', 'xpolog', 'xcelen',
       'xilinx', 'xylemi', 'zayogr', 'zimmer', 'zoetis', 'ebayin',
       'salesf'], dtype=object)

In [42]:
len(df_end.Names.unique())

439

In [43]:
# df_end.to_csv('merged_df_messy.csv')

In [44]:
# df_end.to_csv('largers_messy.csv')